module Map exposing (..)

import Html exposing (..)

camps = [("Abstract Abode - center circle","[re]connect [re]connection temple")
        ,("Abstract Abode - center circle","[re]connect chameleons closet")
        ,("Abstract Abode - center circle","[re]connect humans of now")
        ,("Abstract Abode - center circle","[re]connect treatment tent")
        ,("Abstract Abode - center circle","[re]connect inside out")
        ,("Abstract Abode - center circle","[re]connect living room")
        ,("Abstract Abode - center circle","[re]connect vesica")
        ,("Abstract Abode - center circle","[re]connect sanctuary living room")
        ,("Abstract Abode - center circle","[re]connect gul stue")
        ,("Abstract Abode - center circle","[re]connect spiritual nomads")
        ,("Abstract Abode - center circle","[re]connect glow stone")
        ,("A1 - camp circle","[re]connect private camping")
        ,("A1 - camp circle","[re]connect Borderland Post office")
        ,("A2 - camp circle","[re]connect private camping")
        ,("A2 - camp circle","[re]connect forgotten dream")
        ,("A3 - camp circle","Sensorial POP-UP experience Camp tents, kitchen")
        ,("A3 - camp circle","Big Boy Balkans Big Band The Living Room")
        ,("A3 - camp circle","Camp Keksi Beach Fun Times")
        ,("A4 - camp circle","TuttiFrutti Harmonograph, Tribe of Mentors")
        ,("A4 - camp circle","ElDorado WaterWake Solar Zipline")
        ,("A5 - camp circle","[re]connect private camping")
        ,("A5 - camp circle","[re]connect Kitchen")
        ,("A5 - camp circle","The Lingonberry Girls The Lingonberry")
        ,("A6 - camp circle","[re]connect private camping")
        ,("A6 - camp circle","[re]connect project space")
        ,("A6 - camp circle","Favela Rv’s Basecamp by the path way up to the Favelas, 6-7 Rv’s Favela basecamp")
        ,("A6 - camp circle","Calm baby RV’s Wishing Tree")
        ,("Base Space Borough - center circle","The Space Zirkus The Space Zirkus")
        ,("Base Space Borough - center circle","The Space Zirkus Space Backstage Tent")
        ,("Base Space Borough - center circle","The Space Zirkus The Space Timetable")
        ,("Base Space Borough - center circle","Play Clay Video Café Play Clay Video Café")
        ,("Base Space Borough - center circle","Borderland Wellness Club Spa and Resport Wellness Club Spa and resort")
        ,("B1 - camp circle","The coulor café The coulor café")
        ,("B1 - camp circle","The coulor café Lost & Found")
        ,("B1 - camp circle","The coulor café Coffee junction")
        ,("B2 - camp circle","Research Camp (Psyence) Research Camp")
        ,("B2 - camp circle","The coulor café The coulor café")
        ,("B2 - camp circle","Dawn Our own Connecting Space")
        ,("B2 - camp circle","Mazlows piramid Escape room")
        ,("B3 - camp circle","The Space Zirkus Tents and some public spaces inc 6m bell tent")
        ,("B3 - camp circle","Lovers Love life art")
        ,("B3 - camp circle","secret chemists BurnSafe")
        ,("B3 - camp circle","Space Zirkus 6m bell tent")
        ,("B4 - camp circle","The Space Zirkus The Space Container")
        ,("B4 - camp circle","The Space Zirkus Kitchen, Cooking and Dining Area")
        ,("B4 - camp circle","The Space Zirkus Storage and Construction")
        ,("B4 - camp circle","The Space Zirkus Yurt + Bedouin Tent")
        ,("B5 - camp circle","Fuzzynation Fuzzynation")
        ,("B5 - camp circle","Camp Tiny Camp The Sauna Caravan")
        ,("B6 - camp circle","Borderland Wellness Club Borderland Wellness Club")
        ,("Celestial City - center circle","Belle Époque Absinthe Bar by camp Carnifornication Belle Époque")
        ,("Celestial City - center circle","Spank-a-lot - Spanking and Sensory Bar Spank-a-lot")
        ,("Celestial City - center circle","Bodyland Workshop Bodyland")
        ,("Celestial City - center circle","NoName Trashdrumrack (some noize)")
        ,("Celestial City - center circle","Elements Elements plaza")
        ,("Celestial City - center circle","Elements Fire Bar")
        ,("Celestial City - center circle","Elements Air Nation")
        ,("Celestial City - center circle","Elements Elementary Blender")
        ,("Celestial City - center circle","Elements Elementary School")
        ,("Celestial City - center circle","Camp of No Time Clock Tower of No Time + The great wall of colours and textures")
        ,("Celestial City - center circle","Elements Water Nation")
        ,("C1 - camp circle","Elements Camping #1")
        ,("C1 - camp circle","Elements The Kitchen")
        ,("C2 - camp circle","NoName Tents")
        ,("C2 - camp circle","NoName Music Wagon")
        ,("C2 - camp circle","Camp NoCamp Camping, kitchen, community area")
        ,("C3 - camp circle","wadobe Camping")
        ,("C3 - camp circle","Camp of No Time Clock Tower of No Time in C center")
        ,("C3 - camp circle","Elements Camping #2")
        ,("C4 - camp circle","Carnifornication Camping")
        ,("C4 - camp circle","Carnifornication Cooking")
        ,("C4 - camp circle","Bodyland cooking Bodyland")
        ,("C4 - camp circle","Shithole camping")
        ,("C5 - camp circle","Elements Earth Nation: The Cave & HBN kitchen tent")
        ,("C5 - camp circle","Elements Earth Nation: Camping")
        ,("C5 - camp circle","Bodyland Bodyland camping")
        ,("C6 - camp circle","Cube Noir Cube Noir")
        ,("C6 - camp circle","The Witches Burn A witchy pagan atmosphere")
        ,("C6 - camp circle","Insomnia Mini art")
        ,("Dazzling Dwelling - center circle","Camp Serendipity Serendipity Kinbaku Playground")
        ,("Dazzling Dwelling - center circle","QQQ Queer Qastle")
        ,("Dazzling Dwelling - center circle","The Kids Herb Garden")
        ,("Dazzling Dwelling - center circle","The Dying Camp Balls of Bliss")
        ,("Dazzling Dwelling - center circle","Shame Pain Glory The Decadently fancy playhouse")
        ,("Dazzling Dwelling - center circle","PlemPlem Sauna Tent")
        ,("Dazzling Dwelling - center circle","PlemPlem Black Light Lounge")
        ,("Dazzling Dwelling - center circle","Camp Serendipity Camp Serendipity Workshop Lounge")
        ,("Dazzling Dwelling - center circle","MY DICK MY 1000+1 tiny DICK")
        ,("Dazzling Dwelling - center circle","QQQ Queer Qloset")
        ,("Dazzling Dwelling - center circle","Oily Space Mermaids UFO")
        ,("D1 - camp circle","QQQ Queer Plaza")
        ,("D1 - camp circle","QQQ Slut on a stick")
        ,("D1 - camp circle","QQQ QQQ qamping")
        ,("D2 - camp circle","QQQ Heavy Petting Zoo")
        ,("D2 - camp circle","QQQ Naked Lunch Kitchen")
        ,("D2 - camp circle","QQQ Starving Queer Kitchen")
        ,("D2 - camp circle","QQQ/Macho Kitchen Macho Kitchen")
        ,("D3 - camp circle","Oily Space Mermaids UFO")
        ,("D3 - camp circle","PlemPlem privat camping, salon, kitchen, (+bus, car)")
        ,("D3 - camp circle","MY DICK MY 1000+1 tiny DICK kitchen")
        ,("D3 - camp circle","MY 1000+1 tiny DICK camp")
        ,("D4 - camp circle","The Dying Camp The Pancake Oasis")
        ,("D4 - camp circle","The Kids kitchen/tents, herb garden in center")
        ,("D4 - camp circle","sexycool")
        ,("D4 - camp circle","MY DICK MY 1000+1 Dick camp")
        ,("D4 - camp circle","My Dick Camping")
        ,("D5 - camp circle","Shame pain glory Private camping, kitchen, tents")
        ,("D5 - camp circle","Co-Munity Private camping, kitchen, tents")
        ,("D5 - camp circle","JJ and SF Private camping, kitchen, tents")
        ,("D6 - camp circle","Camp Serendipity Camp Serendipity and our Workshop Lounge")
        ,("D6 - camp circle","Oyster Camp Emotional Striptease, Oinkville")
        ,("Enchanted Establishment - center circle","Camp at the End of the Universe The Psychonautic Chilldome")
        ,("Enchanted Establishment - center circle","Camp at the End of the Universe Chilldome Patio Area")
        ,("Enchanted Establishment - center circle","Camp at the End of the Universe Fire spinning space")
        ,("Enchanted Establishment - center circle","Jam Camp Music & Theatre Improv JamSpace")
        ,("Enchanted Establishment - center circle","Camp at the End of the Universe Movement Space")
        ,("Enchanted Establishment - center circle","The might be Espresso Bar Espresso lounge")
        ,("Enchanted Establishment - center circle","SolarPunks Solar Chill dome An insulated 6.2m dome with AC cooling powered by solar!")
        ,("Enchanted Establishment - center circle","Camp at the end of the universe free safety space around fire area")
        ,("E1 - camp circle","Camp at the End of the Universe Camp")
        ,("E1 - camp circle","Camp at the End of the Universe kitchen")
        ,("E1 - camp circle","No Shit Shirlock Camp")
        ,("E2 - camp circle","SolarPunks SolarPunks")
        ,("E2 - camp circle","Less is More")
        ,("E2 - camp circle","La Kris Camp")
        ,("E2 - camp circle","Space Cunt Astrobingo, tarotkort")
        ,("E2 - camp circle","Cooking Corpses Camping incl RV + food camp.")
        ,("E3 - camp circle","Jam Camp Kitchen + bell tent")
        ,("E3 - camp circle","Jam Camp camping")
        ,("E3 - camp circle","Dampsa-hippyvan camping + camper van")
        ,("E3 - camp circle","Uncamp Camp + bar")
        ,("E4 - camp circle","The Hippie Trap Fireballoon")
        ,("E4 - camp circle","Tunnel of 1000 lights")
        ,("E4 - camp circle","Bodyworkers Bodyworks temple")
        ,("E4 - camp circle","Esmeralda`s Esmeralda`s small things")
        ,("E5 - camp circle","Improv Camp Camp + Kitchen, Improv scene")
        ,("E5 - camp circle","Camp Short Camp")
        ,("E5 - camp circle","Rawr & Rest Camp (working name) Camp Rawr & Rest")
        ,("E5 - camp circle","Rawr & Rest Camp (working name) Intercourse Incorporated")
        ,("E6 - camp circle","Pass Camp")
        ,("E6 - camp circle","The Oasis Make-your-own dream house + Camp")
        ,("E6 - camp circle","The holly cup of time 2 Camp + caravan")
        ,("E6 - camp circle","The might be Espresso Bar Camp")
        ,("Flashy Fields - center circle","Feywild Feywomb")
        ,("Flashy Fields - center circle","Temple of Visions Meditation & Ceremony Yurt")
        ,("Flashy Fields - center circle","Plan B Open workshop tent")
        ,("Flashy Fields - center circle","Camp Nonsense Dome think too hard")
        ,("Flashy Fields - center circle","Butterfly Effect Camp Workshop space and camp infrastructure")
        ,("Flashy Fields - center circle","Hokuspokus Tea Town Hygge")
        ,("F1 - camp circle","Fjorderlings Borderland playpark and ChillLounge")
        ,("F1 - camp circle","Polyrose Camping, Workshops")
        ,("F1 - camp circle","Plan B Camping, workshops")
        ,("F2 - camp circle","Highbearnation/Elements camping De Waarde tent")
        ,("F2 - camp circle","Feywild Feywomb")
        ,("F2 - camp circle","Creature Creators improv, blarping, character creation, acting, comedy shows")
        ,("F2 - camp circle","Mjau camping, being")
        ,("F3 - camp circle","Camp Eclectica Chill vibes/Camping.")
        ,("F3 - camp circle","That was it N/A")
        ,("F3 - camp circle","Rainbow Midwives Bubbly birth of Unicorns/camping")
        ,("F3 - camp circle","GlowFurDome")
        ,("F4 - camp circle","Other End of the Universe Camping")
        ,("F4 - camp circle","The FLOWer garden Cozy home-space (big kitchen and chill out space with roofs), sharing flow and chill vibes")
        ,("F4 - camp circle","Kinky leif camping")
        ,("F5 - camp circle","Camp Nonsense Camping, kitchen, dome")
        ,("F5 - camp circle","Frogs Against Humanity x")
        ,("F5 - camp circle","the camp camp camping.")
        ,("F5 - camp circle","Butterfly Effect Camp Camping")
        ,("F6 - camp circle","Temple of Visions Camp & Kitchen/Dining tent")
        ,("Gentle Glade - center circle","Kidsville Kidsville big white play tent")
        ,("Gentle Glade - center circle","Kidsville Kidsville vegetarian meal plan")
        ,("Gentle Glade - center circle","Kidsville Kidsville bar")
        ,("Gentle Glade - center circle","Kidsville Carl’s Dome")
        ,("Gentle Glade - center circle","Kidsville The Tipi / Parents Playground")
        ,("Gentle Glade - center circle","Kidsville The @sshole")
        ,("Gentle Glade - center circle","The wild sacred Fire: The Lightbringers Wild Sacred Fire’s main kitchen")
        ,("Gentle Glade - center circle","The wild sacred Fire: The Lightbringers The Circle of Unity")
        ,("Gentle Glade - center circle","The Clear Frequency 100 % sober space (workshop tent)")
        ,("Gentle Glade - center circle","The Saddu Camp (the two Saddhus in the camp will be camping in G5 which is then full) The New Eccentric Altar")
        ,("Gentle Glade - center circle","Camp Gayvid Obama/Biden vibe zone")
        ,("G1 - camp circle","Free Campers & Some Cloth Free Private camping")
        ,("G1 - camp circle","The clear frequency TCF member camping space")
        ,("G1 - camp circle","The Clear frequency TCF kitchen structure etc")
        ,("G1 - camp circle","Beyoncé Camps, tents, chillout, workshops")
        ,("G2 - camp circle","Kidsville Space for small camps (2-6 ppl)")
        ,("G2 - camp circle","Kidsville: Camp Ohana Pipe Dream")
        ,("G2 - camp circle","Kidsville: Snuffle Pups Shaded chill space")
        ,("G2 - camp circle","Kidsville: The mixed experience The mixed experience")
        ,("G3 - camp circle","Kidsville: Camp Hostile The Roastery")
        ,("G3 - camp circle","Kidsville Space for small camps (2-6 ppl)")
        ,("G4 - camp circle","Kidsville: The ‘mixed experience’ The ‘mixed experience’")
        ,("G4 - camp circle","Kidsville Space for small camps (2-6 ppl)")
        ,("G5 - camp circle","Kidsville: Camp I am So Bored")
        ,("G5 - camp circle","Kidsville Camp Hang Around")
        ,("G5 - camp circle","Kidsville: Camp Nightlight Kidsville bar!")
        ,("G5 - camp circle","Kidsville; The terrible twos Some minor installations")
        ,("G6 - camp circle","Camp burnt toast II Electric art cars, radios, radio repeater station, The Orb, Digital Mandela, CO2 neutral Borderland")
        ,("G6 - camp circle","Lazy Noodles camp Lazy Noodles")
        ,("G6 - camp circle","The wild sacred Fire: The Lightbringers Space for inhabitants of The WSF")
        ,("G6 - camp circle","Beduin Boudoir (will be moved to RV zone, just put here for preliminery info)")
        ,("G6 - camp circle","Camels and snakes")
        ,("H1 - camp circle","aVANgers Group of 5 free Campervans")
        ,("H1 - camp circle","aVANgers SHade in the centre")
        ,("H2 - camp circle","Less is More")
        ,("H4 - camp circle","{Adult} LittleSpace [beta] Place only used, if not needed for bigger camps. (workshops, camping, play sessions.)")
        ,("H6 - camp circle","Space travel jam jamming sessions, small sound system, tent and shady area with coziness and gemütlichkeit")
        ,("X1 - camp circle","Theater of Touch Theater of Touch")
        ,("X1 - camp circle","Tantric Tipi The Tantric Tipi 2.0")
        ,("X1 - camp circle","Tapestry Weaver’s Guild Grand Treasure Hunt")
        ,("X2 - camp circle","Foxhole The Foxhole")
        ,("X2 - camp circle","Foxhole Kitchen")
        ,("X2 - camp circle","Foxhole Personal tents")
        ,("X3- camp circle","Silly Sanctuary Silly Sanctuary")
        ,("X3- camp circle","Silly Sanctuary Craft Maddness")
        ,("X3- camp circle","Silly Sanctuary Magical tree")
        ,("X4 - camp circle","Silly Sanctuary")
        ,("X4 - camp circle","Kitchen and Glamping tents")
        ,("X4 - camp circle","Dressing room and bathroom")
        ,("X5 - camp circle","Zine better days The Hiding place")
        ,("X6 - camp circle","Temple of Tokamak")
        ,("X6 - camp circle","The Wild Sacred Fire: Bringer of darkness Extended camp for partyshamans")
        ,("X7 - camp circle","Zip-Ties Enginerding, Inc (option 2) Sticks, Ropes & Lights")
        ,("X7 - camp circle","Butterfly effect camp Camp and art")
        ,("X8 - camp circle","The Neighbours Fields of flowes")
        ,("X8 - camp circle","The Village Wishing tree")
        ,("X8 - camp circle","Coffe Camp Music machine")
        ,("X8 - camp circle","BFFriends Surprise neoncorner & spontatnious art")
        ,("X9 - camp circle","Chill Out Queen Favelas")
        ,("X9 - camp circle","The Little Hut of Infinity Vibrations")
        ,("X9 - camp circle","The other village QUEENS GLITTER")
        ,("X9 - camp circle","The chill out shady lounge The Little Hut of Infinity Vibrations")
        ,("X9 - camp circle","The sailcanvas-shade HoLy Coffe!")
        ,("X10 - camp circle","Tea By the SEA")
        ,("X10 - camp circle","Tea tent, Lighthouse")
        ,("X10 - camp circle","Tea by the Sea camp village")
        ,("X11 - camp circle ","Tentacle Tiki Lounge")
        ,("X11 - camp circle ","Fugtiga Frallan/ Wet Baguette")
        ,("X11 - camp circle ","The Brainy Bunch (The Brain Machine) – camp The Brain Machine + Labyrinth")
        ,("X12 - camp circle","Camp Azylum")
        ,("X12 - camp circle","Azylum Kitchen")
        ,("X12 - camp circle","The Brainy Bunch (The Brain Machine) – camp")
        ,("X12 - camp circle","The Brainy Azylum Co-created Chillout")
        ,("X13 - camp circle","Camp Croquis")
        ,("X13 - camp circle","Camp Croquis Platform and Guided sessions: Croquis & Collaborative Arts")
        ,("X13 - camp circle","Camp Croquis Confession session")
        ,("X13 - camp circle","Camp Croquis The bar of Requirement - A doubble bar espeziale-surprise")
        ,("X14 - camp circle","Wonderland Tent / structure for workshops")
        ,("X14 - camp circle","Wonderland")
        ,("X14 - camp circle","Wonderland Kitchen tent")
        ,("X15 - camp circle","Tricky Trip TP Tricky Trip ft. Space Mountain")
        ,("X15 - camp circle","The Spectators")
        ,("X15 - camp circle","The trip stoppers")
        ,("X16 - camp circle","Orgyrobot Orgyrobot")
        ,("X17 - camp circle","Camp Short Introvert’s Recharging Station")
        ,("X17 - camp circle","Zip-Ties Enginerding, Inc (option 1) Sticks, Ropes & Lights")
        ,("X19 - camp circle","The Miau-Miau Lounge The Glowfur Dome")
        ,("X19 - camp circle","Barsuk & Friend")
        ,("X21 - camp circle","The Mighty Jungle")
        ,("X23 - camp circle","The federal Government of the Borderland The Supreme Court")
        ,("X24 - camp circle","Camp of Failure common chillout area, private space")
        ,("X25 - camp circle","Champ pain Chill out space")
        ,("X25 - camp circle","Champ pain Kitchen and hangout")
        ,("X27 - camp circle","Shadow bunnies BunnyHorse Bar")
        ,("X27 - camp circle","Shadow bunnies Bar and camp lounge area")
        ,("X28 - camp circle","The Edge The Shameless Whorehouse")
        ,("X28 - camp circle","The Porn Cinema")
        ,("X29 - camp circle","The Edge kitchen / personal camping")
        ,("X30 - camp circle","The Mighty Jungle Lounge, music,")
        ,("X30 - camp circle","The retirement home: elders of whine-on")
        ,("X30 - camp circle","TIG")
        ,("X30 - camp circle","Nadja")
        ,("X31 - camp circle","The Glade camp The Glade")
        ,("X31 - camp circle","Family Hüppin Magic Key Tree")
        ,("X31 - camp circle","Family Hüppin Magic garden")
        ,("X31 - camp circle","Family Hüppin Kitchen and Sructure")
        ,("X32 - camp circle","Shadow bunnies kitchen")
        ,("X32 - camp circle","Shadow bunnies")
        ,("X33 - camp circle","Shadow bunnies")
        ,("X33 - camp circle","Muumimaa Camp [ Kitchen & Sleeps ]")
        ,("X34 - camp circle","Muumimaa Camp [ Kitchen & Sleeps ]")
        ,("X34 - camp circle","Turbo Libido [ Kitchen & Sleeps ]")
        ,("SC1","Torpet Tiny stage")
        ,("SC1","Outer Bass Ship large van, producing shaking grounds")
        ,("SC2","Deep Dive Sacred Shrine")
        ,("SC3","The Glade")]

viewMap : List (Html msg)
viewMap = [ text "hello" ]
